import{a as L,S as w,i as u}from"./assets/vendor-f736e62a.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const b="43416172-86a986f8fd379e5189cb30c8e",v="https://pixabay.com/api/";async function f(s,e){try{const o=await L.get(v,{params:{key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}});if(!o.data.hits.length)throw new Error("No images found");return o.data}catch(o){throw new Error(o.message)}}const h=document.querySelector(".loader");function p(s){return s.map(e=>`<li class="list-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}">
        </a>

        <div class="list-item-info">
          <p><strong>Likes</strong> <span>${e.likes}</span></p>
          <p><strong>Views</strong> <span>${e.views}</span></p>
          <p><strong>Comments</strong> <span>${e.comments}</span></p>
          <p><strong>Downloads</strong> <span>${e.downloads}</span></p>
        </div>
      </li>`).join("")}function m(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}let n=1;const y=new w(".images-list a");let i=null;const S=document.querySelector(".search-form"),q=document.querySelector(".search-form-input");document.querySelector(".search-form-button");const a=document.querySelector(".images-list"),c=document.querySelector(".button-load");S.addEventListener("submit",P);c.addEventListener("click",E);async function P(s){s.preventDefault(),m(),c.classList.add("is-hidden"),a.innerHTML="",n=1,i=s.currentTarget.elements.search.value.trim();try{if(!i){u.warning({position:"topRight",message:"Please write something! "});return}const e=await f(i,n);if(e.hits.length===0)return u.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});a.innerHTML=p(e.hits),y.refresh(),e.totalHits>15&&c.classList.remove("is-hidden")}catch(e){console.log(e)}finally{g()}q.value=""}async function E(){m(),n++;try{const{hits:s,totalHits:e}=await f(i,n);a.insertAdjacentHTML("beforeend",p(s)),y.refresh();const{height:o}=a.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),Math.ceil(e/15)===n&&(c.classList.add("is-hidden"),u.info({position:"topRight",message:"We're sorry, but you've reached the end of results",maxWidth:"432"}))}catch(s){console.log(s)}finally{g()}}
//# sourceMappingURL=commonHelpers.js.map
