import{a as L,S as w,i as l}from"./assets/vendor-f736e62a.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const b="43416172-86a986f8fd379e5189cb30c8e",v="https://pixabay.com/api/";async function f(r,e){try{const s=await L.get(v,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}});if(!s.data.hits.length)throw new Error("No images found");return s.data}catch(s){throw new Error(s.message)}}const h=document.querySelector(".loader");function p(r){return r.map(e=>`<li class="list-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}">
        </a>

        <div class="list-item-info">
          <p><strong>Likes</strong> <span>${e.likes}</span></p>
          <p><strong>Views</strong> <span>${e.views}</span></p>
          <p><strong>Comments</strong> <span>${e.comments}</span></p>
          <p><strong>Downloads</strong> <span>${e.downloads}</span></p>
        </div>
      </li>`).join("")}function m(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}let n=1;const y=new w(".images-list a");let i=null;const S=document.querySelector(".search-form"),q=document.querySelector(".search-form-input");document.querySelector(".search-form-button");const d=document.querySelector(".images-list"),u=document.querySelector(".button-load");S.addEventListener("submit",P);u.addEventListener("click",E);async function P(r){r.preventDefault(),m(),n=1,i=r.currentTarget.elements.search.value.trim();try{if(!i)return l.error({position:"topRight",message:"Please write something! "});const e=await f(i,n);if(e.hits.length===0)return l.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});d.innerHTML=p(e.hits),y.refresh(),e.totalHits>15&&u.classList.remove("is-hidden")}catch(e){console.log(e)}finally{g()}q.value=""}async function E(){m(),n++;try{const{hits:r,totalHits:e}=await f(i,n);d.insertAdjacentHTML("beforeend",p(r)),y.refresh();const{height:s}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),Math.ceil(e/15)===n&&(u.classList.add("is-hidden"),l.info({position:"topRight",message:"We're sorry, but you've reached the end of results",maxWidth:"432"}))}catch(r){console.log(r)}finally{g()}}
//# sourceMappingURL=commonHelpers.js.map
